name: Deploy changes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: |
        echo "::add-mask::${{ secrets.UPDATE_KEY }}"
        curl  --fail-with-body --show-error -X POST -d "key=${{ secrets.UPDATE_KEY }}" https://yarlswip.l3p3.de/site-update.txt
